# Generated by Django 5.2 on 2025-06-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated/')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='home.chat')),
            ],
        ),
    ]
