# Generated by Django 5.2 on 2025-06-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='/user_images/majestic-mountain-peak-tranquil-winter-landscape-generated-by-ai.jpg', upload_to='user_images/'),
        ),
    ]
